development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  database: <%= ENV['MYSQL2_DATABASE_DEVELOPMENT'] %>
  username: <%= ENV['MYSQL2_USERNAME_DEVELOPMENT'] %>
  password: <%= ENV['MYSQL2_PASSWORD_DEVELOPMENT'] %>
  host: <%= ENV['MYSQL2_HOST_DEVELOPMENT'] %>

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  database: <%= ENV['MYSQL2_DATABASE_TEST'] %>
  username: <%= ENV['MYSQL2_USERNAME_TEST'] %>
  password: <%= ENV['MYSQL2_PASSWORD_TEST'] %>
  host: <%= ENV['MYSQL2_HOST_TEST'] %>

production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  database: <%= ENV['MYSQL2_DATABASE_PRODUCTION'] %>
  username: <%= ENV['MYSQL2_USERNAME_PRODUCTION'] %>
  password: <%= ENV['MYSQL2_PASSWORD_PRODUCTION'] %>
  host: <%= ENV['MYSQL2_HOST_PRODUCTION'] %>